vich_uploader:
    db_driver: orm
    mappings:
        galerie_photos:
            uri_prefix: /uploads/galerie
            upload_destination: '%kernel.project_dir%/public/uploads/galerie'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service_photos:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
                
        category_photos:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true